#ifndef __MY_SPI_H__
#define __MY_SPI_H__

#include "main.h"

/* Bit-bang mapping for AD9833: SCLK=PA7, SDATA=PA5, FSYNC1=PA6, FSYNC2=PA15 */
#define AD9833_SPI_SCK_L HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET)
#define AD9833_SPI_SCK_H HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET)
#define AD9833_SPI_SDA_L HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET)
#define AD9833_SPI_SDA_H HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET)
#define AD9833_SPI_CS1_L HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_RESET)
#define AD9833_SPI_CS1_H HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_SET)
#define AD9833_SPI_CS2_L HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, GPIO_PIN_RESET)
#define AD9833_SPI_CS2_H HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, GPIO_PIN_SET)
                         

void AD9833_SPI_16bit_Write(uint16_t data);

#endif
